CREATE DATABASE college;
create database xyz;

DROP DATABASE xyz;

CREATE DATABASE college;
USE college;
CREATE TABLE student(
	roll_no INT,
    name VARCHAR(30),
    age INT
);

-- ROWS == TUPLES
INSERT INTO student
VALUES
(699, "kanpri", 12),
(966, "kan", 15);


--  SHOW THE CONTENTS IN THE STUDENT SHEET 
SELECT * FROM student;

-- DATABASE QUERRIES 
CREATE DATABASE IF NOT EXISTS College;
CREATE DATABASE IF NOT EXISTS instagram; 

DROP DATABASE IF EXISTS instagram;

-- WILL SHOW ALL THE DATABASES 
SHOW DATABASES;

USE college;
SHOW TABLES;

CREATE DATABASE IF NOT EXISTS instagram;
USE instagram;
-- WILL SHOW ALL THE TABLES IN THE SELECTE FOLDER
SHOW TABLES;

SHOW DATABASES;


USE instagram;
-- CREATE --- KISI BHI TABLE KE LIYE USK SCHEMA DECIDE KARNA 

CREATE TABLE user( 		-- USER NAAM KA TABLE CREATE KARO
	id INT,
    age INT,
    name VARCHAR(30) NOT NULL, 		-- TUM ISSEY KABHI KHALI NAHI CHOD SAKTE 
    email VARCHAR(50) UNIQUE,		-- eVERYTHING WILL BE UNIQUE
    followers INT DEFAULT 0,
    following INT,
    CONSTRAINT age_check CHECK (age >= 13),
-- KEYS - SPECIAL COLUMNS IN A TABLE
	-- PK CAN NEITHER BE DUPLICATE NOR NULL 
    PRIMARY KEY(id)	-- MAKES A COLUMN UNIQUE AND NOT NULL CAN BE USED FOR ONLY ONE COLUMNS
);

INSERT INTO user
(id, age, name)
VALUES
(7,18), 	-- WILL THROW AN ERROR DUE TO NO NAME 
(2,20, "random");	--  WILL THROW AN ERROR 


CREATE TABLE Posts(
	id INT PRIMARY KEY,
    content VARCHAR(100),
    user_id INT,
    
    -- FK CAN BE DUPLICATES AS WELL AS NULL
    -- CAN HAVE MULTIPLE FK'S
    FOREIGN KEY (user_id) REFERENCES user(id)		-- HUMARI JO COLUMN HAI user_id WOH HUMARE user TABLE KI ID COLUMN SE VALUE LETI HAI 
);

-- ER DIAGRAM / RELATIONS(TABLES)

